CREATE TABLE Clients(
Id int NOT NULL IDENTITY(1,1) PRIMARY KEY,
Username VARCHAR(50) NOT NULL UNIQUE,
Password TEXT NOT NULL,
FirstName TEXT NOT NULL,
LastName TEXT NOT NULL,
CardNumber TEXT NOT NULL)
GO
 